---
# tasks file for docker

- name: Install required packages
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    update_cache: yes

- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /etc/apt/keyrings/docker.gpg

- name: add Docker repo
  shell: "echo 'deb [signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable' | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null"

- name: Install required packages
  apt:
    name: containerd.io
    state: present
    update_cache: yes

- name: containerd config file
  shell: containerd config default | sudo tee /etc/containerd/config.toml
  notify: Restart containerd

- name: change systemd 
  shell: sudo sed -i 's/ SystemdCgroup = false/ SystemdCgroup = true/' /etc/containerd/config.toml
  notify: Restart containerd

