- hosts: k8master
  become: yes
  tasks:
    - name: Copy docker repo script
      copy:
        src: repo.sh 
        dest: $HOME/repo.sh
        mode: 654

    - name: run shell script to add docker repo
      shell: $HOME/repo.sh  