- hosts: k8cluster
  become: yes

  roles:
    - docker
    - k8dependencies
    - kubeadm
    - kubelet
    

- hosts: k8master
  become: yes
  roles:    
    - kubectl
    - control_plane
    

   
