---
- hosts: k8master
  become: yes
  tasks:

   - name: install APT Transport HTTPS
     apt:
       name: apt-transport-https
       state: present

   - name: add Kubernetes apt-key
     apt_key:
       url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key 
       state: present
       keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg



   - name: add Kubernetes' APT repository
     shell: "echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list"


   - name: install k8 packages
     apt:
       name: 
        - kubelet
        - kubeadm
        - kubectl
       state: present
       update_cache: yes

   - name: mark package as held
     shell: sudo apt-mark hold kubelet kubeadm kubectl
  
   - name: bridge
     copy:
       src: bridge.sh
       dest: $HOME/bridge.sh
       mode: 0755
  
   - name: run brige script
     shell: $HOME/bridge.sh

  
